# Default values for kubeauthentication.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
#  repository: master.cloud.com/kubeauthentication
  tag: latest
  pullPolicy: Always
  port: 8001

service:
  type: ClusterIP
  port: 8001

extraEnvVars:
  - name: KEYCLOAK_SERVER_URI
    valueFrom:
      secretKeyRef:
        name: oauth-secrets
        key: OAUTH_SERVER_URI
  - name: CLIENT_ID
    valueFrom:
      secretKeyRef:
        name: oauth-secrets
        key: OIDC_CLIENT_ID
  - name: CLIENT_SECRET
    valueFrom:
      secretKeyRef:
        name: oauth-secrets
        key: OIDC_CLIENT_SECRET
  - name: OAUTH_REALM
    valueFrom:
      secretKeyRef:
        name: oauth-secrets
        key: OAUTH_REALM
  - name: ACTIVE_PROFILE
    valueFrom:
      secretKeyRef:
        name: oauth-secrets
        key: ACTIVE_PROFILE

privateReg:
  enabled: true
  secret: regcred

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-redirect-from: "default"
#    nginx.ingress.kubernetes.io/configuration-snippet: |
#      proxy_redirect https://master.cloud.com https://master.cloud.com;
#      proxy_redirect http://master.cloud.com https://master.cloud.com;
#      #proxy_redirect ~^https(.*)(redirect_uri=)(http)(.*) https$1$2https$4; #Edit the location header
  path: /
  hosts:
    - master.cloud.com
  tls:
    - secretName: appingress-certificate
      hosts:
        - master.cloud.com

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
