# Default values for kubeauthentication.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
#  repository: master.cloud.com/kubeauthentication
  tag: latest
  pullPolicy: Always
  port: 8001

service:
  type: ClusterIP
  port: 8001

secret:
  enabled: true

env:
  enabled: true
  normal: {}
  secret:
    CLIENT_ID: __CLIENT_ID__
    CLIENT_SECRET: __CLIENT_SECRET__

privateReg:
  enabled: true
  secret: regcred

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-redirect-from: "default"
#    nginx.ingress.kubernetes.io/configuration-snippet: |
#      proxy_redirect https://master.cloud.com https://master.cloud.com;
#      proxy_redirect http://master.cloud.com https://master.cloud.com;
#      #proxy_redirect ~^https(.*)(redirect_uri=)(http)(.*) https$1$2https$4; #Edit the location header
  path: /
  hosts:
    - master.cloud.com
  tls:
    - secretName: appingress-certificate
      hosts:
        - master.cloud.com

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
