server:
  tomcat:
    use-relative-redirects: true
oauth:
  clientId: ${CLIENT_ID}
  clientSecret: ${CLIENT_SECRET}
  realm: Username-Password-Authentication
  audience: https://skmaji.auth0.com/userinfo
  authorizeUrl: https://skmaji.auth0.com/authorize
  tokenUrl: https://skmaji.auth0.com/oauth/token
  userInfoUrl: https://skmaji.auth0.com/userinfo
  clientName: OAuth0
  jwkUrl: https://skmaji.auth0.com/.well-known/jwks.json
  registrationId: auth0
  issuerUrl: https://skmaji.auth0.com
  tokenEndpoint: /oauth/token
  passwordGrantType: http://auth0.com/oauth/grant-type/password-realm