spring:
  config:
    import: configtree:/home/sumit/test/
server:
  tomcat:
    use-relative-redirects: true
oauth:
  clientId: C3UHISO3z60iF1JLG8L7VPUSWOASrJfO
  clientSecret:
  realm: Username-Password-Authentication
  audience: https://skmaji.auth0.com/userinfo
  authorizeUrl: https://skmaji.auth0.com/authorize
  tokenUrl: https://skmaji.auth0.com/oauth/token
  userInfoUrl: https://skmaji.auth0.com/userinfo
  clientName: OAuth0
  jwkUrl: https://skmaji.auth0.com/.well-known/jwks.json
  registrationId: auth0
  issuerUrl: https://skmaji.auth0.com
  tokenEndpoint: /oauth/token
  passwordGrantType: http://auth0.com/oauth/grant-type/password-realm